Probando el DSL con un menú, incluyendo el precio de los platos:
Probando la clase Plato_DSL

Menu_DSL
  Probando el DLS
    Probando la clase Menu_DSL (FAILED - 1)

Failures:

  1) Menu_DSL Probando el DLS Probando la clase Menu_DSL
     Failure/Error:
       componente "Hamburguesa especial de la casa",
       	:Precio => 4.25

     NoMethodError:
       undefined method `componente' for #<Menu_DSL:0x000055cf2e6f3dc8>
       Did you mean?  Complex
     # ./spec/alimentacion_spec.rb:754:in `block (4 levels) in <top (required)>'
     # ./lib/alimentacion/menu_dsl.rb:13:in `instance_eval'
     # ./lib/alimentacion/menu_dsl.rb:13:in `initialize'
     # ./spec/alimentacion_spec.rb:752:in `new'
     # ./spec/alimentacion_spec.rb:752:in `block (3 levels) in <top (required)>'

Finished in 0.03367 seconds (files took 0.20124 seconds to load)
61 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:751 # Menu_DSL Probando el DLS Probando la clase Menu_DSL