Alimentos   Devolviendo el nombre del alimento   Devolviendo las proteinas del alimento   Devolviendo los carbohidratos del alimento   Devolviendo los lípidos del alimento   Devolviendo los gases del alimento   Devolviendo el uso de terreno del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo el uso de terreno del alimento
     Failure/Error: expect(@alimento1.terreno).to eq(3.4)

     NoMethodError:
       undefined method `terreno' for #<Alimentos:0x0000559d445eb7f8>
     # ./spec/alimentacion_spec.rb:51:in `block (2 levels) in <top (required)>'

Finished in 0.00331 seconds (files took 0.12376 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:50 # Alimentos Devolviendo el uso de terreno del alimento