Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min (FAILED - 1)
Failures:

  1) Lista Enumerando listas de alimentos Método min
     Failure/Error: expect(@lista2.min).to eq(@carne)

     NoMethodError:
       undefined method `min' for #<Lista:0x0000559f24b0a4f0>
     # ./spec/alimentacion_spec.rb:250:in `block (3 levels) in <top (required)>'

Finished in 0.01636 seconds (files took 0.21932 seconds to load)
29 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:249 # Lista Enumerando listas de alimentos Método min