Menu_DSL   Probando el DLS     Probando la clase Menu_DSL (FAILED - 1)
Failures:

  1) Menu_DSL Probando el DLS Probando la clase Menu_DSL
     Failure/Error: descripcion "Hamburguesa, carne y tarta"

     NoMethodError:
       undefined method `descripcion' for #<Menu_DSL:0x000055de82a088e8 @lista_platos=[], @precios_menu=[]>
     # ./spec/alimentacion_spec.rb:753:in `block (4 levels) in <top (required)>'
     # ./lib/alimentacion/menu_dsl.rb:13:in `instance_eval'
     # ./lib/alimentacion/menu_dsl.rb:13:in `initialize'
     # ./spec/alimentacion_spec.rb:752:in `new'
     # ./spec/alimentacion_spec.rb:752:in `block (3 levels) in <top (required)>'

Finished in 0.03375 seconds (files took 0.20238 seconds to load)
61 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:751 # Menu_DSL Probando el DLS Probando la clase Menu_DSL