Alimentos   Devolviendo el nombre del alimento   Devolviendo las proteinas del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo las proteinas del alimento
     Failure/Error: expect(@alimento1.proteinas).to eq(5.3)

     NoMethodError:
       undefined method `proteinas' for #<Alimentos:0x00005627acbf8e28>
     # ./spec/alimentacion_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.00261 seconds (files took 0.1403 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:18 # Alimentos Devolviendo las proteinas del alimento