Plato_DSL   Probando el DSL     Probando la clase Plato_DSL (FAILED - 1)
Failures:

  1) Plato_DSL Probando el DSL Probando la clase Plato_DSL
     Failure/Error: nombre "Hamburguesa especial de la casa"

     NoMethodError:
       undefined method `nombre' for #<Plato_DSL:0x00005570ee6c1308>
     # ./spec/alimentacion_spec.rb:658:in `block (4 levels) in <top (required)>'
     # ./lib/alimentacion/plato_dsl.rb:18:in `instance_eval'
     # ./lib/alimentacion/plato_dsl.rb:18:in `initialize'
     # ./spec/alimentacion_spec.rb:657:in `new'
     # ./spec/alimentacion_spec.rb:657:in `block (3 levels) in <top (required)>'

Finished in 0.03113 seconds (files took 0.20554 seconds to load)
60 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:656 # Plato_DSL Probando el DSL Probando la clase Plato_DSL