Probando el nombre del alimento:
Plato_DSL
  Probando el DSL
    Probando la clase Plato_DSL (FAILED - 1)

Failures:

  1) Plato_DSL Probando el DSL Probando la clase Plato_DSL
     Failure/Error: alimento :descripcion => "carne de vaca", :gramos => 100

     NoMethodError:
       undefined method `alimento' for #<Plato_DSL:0x000055d404548f70>
     # ./spec/alimentacion_spec.rb:659:in `block (4 levels) in <top (required)>'
     # ./lib/alimentacion/plato_dsl.rb:18:in `instance_eval'
     # ./lib/alimentacion/plato_dsl.rb:18:in `initialize'
     # ./spec/alimentacion_spec.rb:657:in `new'
     # ./spec/alimentacion_spec.rb:657:in `block (3 levels) in <top (required)>'

Finished in 0.03537 seconds (files took 0.20247 seconds to load)
60 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:656 # Plato_DSL Probando el DSL Probando la clase Plato_DSL