Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail     Probando el método extract_head     Probando el método extract_tail     Probando el método insert (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método insert
     Failure/Error: @lista.insert([@carne,@queso,@huevos])

     NoMethodError:
       undefined method `insert' for #<Lista:0x0000560b75dc9c28 @head=nil, @tail=nil>
       Did you mean?  inspect
     # ./spec/alimentacion_spec.rb:131:in `block (3 levels) in <top (required)>'

Finished in 0.00669 seconds (files took 0.14773 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:130 # Lista Probando la lista doblemente enlazada Probando el método insert