Alimentos   Devolviendo el nombre del alimento   Devolviendo las proteinas del alimento   Devolviendo los carbohidratos del alimento   Devolviendo los lípidos del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo los lípidos del alimento
     Failure/Error: expect(@alimento1.lipidos).to eq(30.0)

     NoMethodError:
       undefined method `lipidos' for #<Alimentos:0x0000564cc96d9040>
     # ./spec/alimentacion_spec.rb:35:in `block (2 levels) in <top (required)>'

Finished in 0.00304 seconds (files took 0.12909 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:34 # Alimentos Devolviendo los lípidos del alimento