Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas (FAILED - 1)

Failures:

  1) Plato Probando la clase Plato Obteniendo el porcentaje de proteínas
     Failure/Error: expect(@plato.porcentaje_proteinas).to eq(23.11)

     NoMethodError:
       undefined method `porcentaje_proteinas' for #<Plato:0x00005586ba870ff0>
     # ./spec/alimentacion_spec.rb:304:in `block (3 levels) in <top (required)>'

Finished in 0.01923 seconds (files took 0.23746 seconds to load)
38 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:303 # Plato Probando la clase Plato Obteniendo el porcentaje de proteínas