Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos
    Obteniendo valor calórico total del plato
    Obteniendo el plato formateado

Eficiencia_Energetica
  Probando la clase Eficiencia_Energetica
    Obteniendo gases anuales
    Obteniendo gases diarios (FAILED - 1)

Failures:

  1) Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo gases diarios
     Failure/Error: expect(@eficiencia.emisiones_gases_diarios).to eq(0.008)

     NoMethodError:
       undefined method `emisiones_gases_diarios' for #<Eficiencia_Energetica:0x0000555f436863a0>
       Did you mean?  emisiones_gases_anuales
     # ./spec/alimentacion_spec.rb:354:in `block (3 levels) in <top (required)>'

Finished in 0.01793 seconds (files took 0.18199 seconds to load)
44 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:353 # Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo gases diarios