Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail     Probando el método extract_head     Probando el método extract_tail (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método extract_tail
     Failure/Error: @lista.extract_tail()

     NoMethodError:
       undefined method `extract_tail' for #<Lista:0x00005561c341bbb0>
       Did you mean?  extract_head
     # ./spec/alimentacion_spec.rb:125:in `block (3 levels) in <top (required)>'

Finished in 0.00666 seconds (files took 0.14775 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:123 # Lista Probando la lista doblemente enlazada Probando el método extract_tail