Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail     Probando el método extract_head (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método extract_head
     Failure/Error: @lista.extract_head()

     NoMethodError:
       undefined method `extract_head' for #<Lista:0x0000563e54d47a18>
     # ./spec/alimentacion_spec.rb:119:in `block (3 levels) in <top (required)>'

Finished in 0.00614 seconds (files took 0.15179 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:118 # Lista Probando la lista doblemente enlazada Probando el método extract_head