Alimentos   Devolviendo el alimento formateado   Probando el método valor_energetico (FAILED - 1)   Probando los getters     Devolviendo el nombre del alimento     Devolviendo las proteinas del alimento     Devolviendo los carbohidratos del alimento     Devolviendo los lípidos del alimento     Devolviendo los gases del alimento     Devolviendo el uso de terreno del alimento
Failures:

  1) Alimentos Probando el método valor_energetico
     Failure/Error: expect(@alimento1.valor_energetico).to eq(479.2)

     NoMethodError:
       undefined method `valor_energetico' for #<Alimentos:0x000055908fa6e580>
     # ./spec/alimentacion_spec.rb:68:in `block (2 levels) in <top (required)>'

Finished in 0.00386 seconds (files took 0.12776 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:67 # Alimentos Probando el método valor_energetico