Alimentos   Devolviendo el alimento formateado   Probando el método valor_energetico   Probando los getters     Devolviendo el nombre del alimento     Devolviendo las proteinas del alimento     Devolviendo los carbohidratos del alimento     Devolviendo los lípidos del alimento     Devolviendo los gases del alimento     Devolviendo el uso de terreno del alimento   Calculando los impactos ambientales     Calculando el impacto ambiental de un hombre     Calculando el impacto ambiental de una mujer (FAILED - 1)
Failures:

  1) Alimentos Calculando los impactos ambientales Calculando el impacto ambiental de una mujer
     Failure/Error: expect(@alimento5.impacto_mujer(125,50,56.81,94.34,181.81)).to eq([2.09,2.72])

     NoMethodError:
       undefined method `impacto_mujer' for #<Alimentos:0x000055a418f9b3b8>
       Did you mean?  impacto_hombre
     # ./spec/alimentacion_spec.rb:81:in `block (3 levels) in <top (required)>'

Finished in 0.00584 seconds (files took 0.1323 seconds to load)
10 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:80 # Alimentos Calculando los impactos ambientales Calculando el impacto ambiental de una mujer