Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos (FAILED - 1)

Failures:

  1) Plato Probando la clase Plato Obteniendo el porcentaje de lípidos
     Failure/Error: expect(@plato.porcentaje_lipidos).to eq(21.26)

     NoMethodError:
       undefined method `porcentaje_lipidos' for #<Plato:0x00005570fff5a7d8>
       Did you mean?  porcentaje_hidratos
     # ./spec/alimentacion_spec.rb:312:in `block (3 levels) in <top (required)>'

Finished in 0.01988 seconds (files took 0.19258 seconds to load)
40 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:311 # Plato Probando la clase Plato Obteniendo el porcentaje de lípidos