Comparando alimentos en base a sus proteínas     Operador <= (FAILED - 1)
Failures:

  1) Lista Comparando alimentos en base a sus proteínas Operador <=
     Failure/Error: expect(@queso <= @salmon).to eq(true)

     NoMethodError:
       undefined method `<=' for #<Alimentos:0x000055ecb5bbb848>
       Did you mean?  <=>
     # ./spec/alimentacion_spec.rb:220:in `block (3 levels) in <top (required)>'

Finished in 0.012 seconds (files took 0.22267 seconds to load)
23 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:219 # Lista Comparando alimentos en base a sus proteínas Operador <=