Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método insert_tail
     Failure/Error: @lista.insert_tail(@queso)

     NoMethodError:
       undefined method `insert_tail' for #<Lista:0x0000559fd80059b0>
       Did you mean?  insert_head
     # ./spec/alimentacion_spec.rb:113:in `block (3 levels) in <top (required)>'

Finished in 0.00674 seconds (files took 0.15774 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:112 # Lista Probando la lista doblemente enlazada Probando el método insert_tail