Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos (FAILED - 1)

Failures:

  1) Plato Probando la clase Plato Obteniendo el porcentaje de hidratos
     Failure/Error: expect(@plato.porcentaje_hidratos).to eq(0.74)

     NoMethodError:
       undefined method `porcentaje_hidratos' for #<Plato:0x00005613986144a8>
       Did you mean?  porcentaje_proteinas
     # ./spec/alimentacion_spec.rb:308:in `block (3 levels) in <top (required)>'

Finished in 0.01951 seconds (files took 0.26254 seconds to load)
39 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:307 # Plato Probando la clase Plato Obteniendo el porcentaje de hidratos