Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos
    Obteniendo valor calórico total del plato
    Obteniendo el plato formateado

Eficiencia_Energetica
  Probando la clase Eficiencia_Energetica
    Obteniendo gases anuales
    Obteniendo gases diarios
    Obteniendo uso del terreno (FAILED - 1)

Failures:

  1) Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo uso del terreno
     Failure/Error: expect(@eficiencia.uso_terreno).to eq(9.26)

     NoMethodError:
       undefined method `uso_terreno' for #<Eficiencia_Energetica:0x000055877adc1958>
     # ./spec/alimentacion_spec.rb:358:in `block (3 levels) in <top (required)>'

Finished in 0.01985 seconds (files took 0.24049 seconds to load)
45 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:357 # Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo uso del terreno