Alimentos   Devolviendo el alimento formateado   Probando el método valor_energetico   Probando los getters     Devolviendo el nombre del alimento     Devolviendo las proteinas del alimento     Devolviendo los carbohidratos del alimento     Devolviendo los lípidos del alimento     Devolviendo los gases del alimento     Devolviendo el uso de terreno del alimento   Calculando los impactos ambientales     Calculando el impacto ambiental de un hombre (FAILED - 1)
Failures:

  1) Alimentos Calculando los impactos ambientales Calculando el impacto ambiental de un hombre
     Failure/Error: expect(@alimento5.impacto_hombre(100)).to eq([6.02,17.34])

     NoMethodError:
       undefined method `impacto_hombre' for #<Alimentos:0x000055cb7d30c138>
     # ./spec/alimentacion_spec.rb:77:in `block (3 levels) in <top (required)>'

Finished in 0.00539 seconds (files took 0.12694 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:76 # Alimentos Calculando los impactos ambientales Calculando el impacto ambiental de un hombre