Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos
    Obteniendo valor calórico total del plato
    Obteniendo el plato formateado

Eficiencia_Energetica
  Probando la clase Eficiencia_Energetica
    Obteniendo gases anuales (FAILED - 1)

Failures:

  1) Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo gases anuales
     Failure/Error: expect(@eficiencia.emisiones_gases_anuales).to eq(3.06)

     NoMethodError:
       undefined method `emisiones_gases_anuales' for #<Eficiencia_Energetica:0x000055706a9b0250>
     # ./spec/alimentacion_spec.rb:350:in `block (3 levels) in <top (required)>'

Finished in 0.03302 seconds (files took 0.39733 seconds to load)
43 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:349 # Eficiencia_Energetica Probando la clase Eficiencia_Energetica Obteniendo gases anuales