Creando un menú dietético     Calculando la huella nutricional (FAILED - 1)
Failures:

  1) Eficiencia_Energetica Creando un menú dietético Calculando la huella nutricional
     Failure/Error: expect(@eficiencia.huella_nutricional).to eq(3.0)

     NoMethodError:
       undefined method `huella_nutricional' for #<Eficiencia_Energetica:0x000055a3d8a4aea8>
     # ./spec/alimentacion_spec.rb:637:in `block (3 levels) in <top (required)>'

Finished in 0.02153 seconds (files took 0.16656 seconds to load)
58 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:636 # Eficiencia_Energetica Creando un menú dietético Calculando la huella nutricional