Alimentos   Devolviendo el nombre del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo el nombre del alimento
     Failure/Error: expect(@alimento1.nombre).to eq("Chocolate")

     NoMethodError:
       undefined method `nombre' for #<Alimentos:0x000055c860afc2a0>
     # ./spec/alimentacion_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.00155 seconds (files took 0.11811 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:10 # Alimentos Devolviendo el nombre del alimento