Alimentos   Devolviendo el nombre del alimento   Devolviendo las proteinas del alimento   Devolviendo los carbohidratos del alimento   Devolviendo los lípidos del alimento   Devolviendo los gases del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo los gases del alimento
     Failure/Error: expect(@alimento1.gei).to eq(2.3)

     NoMethodError:
       undefined method `gei' for #<Alimentos:0x000056016adf5888>
       Did you mean?  gem
     # ./spec/alimentacion_spec.rb:43:in `block (2 levels) in <top (required)>'

Finished in 0.00336 seconds (files took 0.13267 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:42 # Alimentos Devolviendo los gases del alimento