Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail     Probando el método extract_head     Probando el método extract_tail     Probando el método insert     Probando el método imprimir (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método imprimir
     Failure/Error: expect(@lista.imprimir).to eq(["(carne vaca,1,2,3,5,4)", "(queso,5,6,7,8,9)", "(huevos,8,7,6,5,4)"])

     NoMethodError:
       undefined method `imprimir' for #<Lista:0x00005625515d9838>
     # ./spec/alimentacion_spec.rb:137:in `block (3 levels) in <top (required)>'

Finished in 0.00711 seconds (files took 0.15413 seconds to load)
17 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:136 # Lista Probando la lista doblemente enlazada Probando el método imprimir