Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos
    Obteniendo valor calórico total del plato
    Obteniendo el plato formateado

Eficiencia_Energetica
  Probando la clase Eficiencia_Energetica
    Obteniendo gases anuales
    Obteniendo gases diarios
    Obteniendo uso del terreno
    Obteniendo la eficiencia energética formateada
    Obteniendo clase y tipo de un objeto
  Comparando distintos platos
    Platos de la dieta española (FAILED - 1)

Failures:

  1) Eficiencia_Energetica Comparando distintos platos Platos de la dieta española
     Failure/Error: expect(@plato <= @plato2).to eq(false)

     NoMethodError:
       undefined method `<=' for #<Plato:0x000055f4554773a0>
       Did you mean?  <=>
     # ./spec/alimentacion_spec.rb:399:in `block (3 levels) in <top (required)>'

Finished in 0.02323 seconds (files took 0.23434 seconds to load)
48 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:378 # Eficiencia_Energetica Comparando distintos platos Platos de la dieta española