Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters (FAILED - 1)
Failures:

  1) Lista Probando la lista doblemente enlazada Probando el método insert_head y los getters
     Failure/Error: @lista.insert_head(@carne)

     NoMethodError:
       undefined method `insert_head' for #<Lista:0x000055837ce75b30 @head=nil, @tail=nil>
     # ./spec/alimentacion_spec.rb:107:in `block (3 levels) in <top (required)>'

Finished in 0.00535 seconds (files took 0.14641 seconds to load)
12 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:106 # Lista Probando la lista doblemente enlazada Probando el método insert_head y los getters

15:58:02 - INFO - Running: spec/alimentacion_spec.rb