Lista   Probando la estructura del nodo   Probando la lista doblemente enlazada     Probando el método insert_head y los getters     Probando el método insert_tail     Probando el método extract_head     Probando el método extract_tail     Probando el método insert     Probando el método imprimir   Probando las cinco dietas     Dieta española en un hombre (FAILED - 1)
Failures:

  1) Lista Probando las cinco dietas Dieta española en un hombre
     Failure/Error: expect(@dieta1.dieta_gases_anuales([150,150,100,33,50,50,50])).to eq(3.08)

     NoMethodError:
       undefined method `dieta_gases_anuales' for #<Lista:0x00005649104623c8>
     # ./spec/alimentacion_spec.rb:154:in `block (3 levels) in <top (required)>'

Finished in 0.00738 seconds (files took 0.14652 seconds to load)
18 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:143 # Lista Probando las cinco dietas Dieta española en un hombre