Alimentos   Devolviendo el nombre del alimento   Devolviendo las proteinas del alimento   Devolviendo los carbohidratos del alimento (FAILED - 1)
Failures:

  1) Alimentos Devolviendo los carbohidratos del alimento
     Failure/Error: expect(@alimento1.hidratos).to eq(47.0)

     NoMethodError:
       undefined method `hidratos' for #<Alimentos:0x000055da2cc97e10>
     # ./spec/alimentacion_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.00284 seconds (files took 0.13064 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:26 # Alimentos Devolviendo los carbohidratos del alimento