Comparando alimentos en base a sus proteínas     Operador <=     Operador ==     Operador >=     Operador <     Operador >     Operador between?   Enumerando listas de alimentos     Método min     Método max     Método collect     Método sort     Método select     Método detect
Plato
  Probando la clase Plato
    Obteniendo el nombre de un plato
    Obteniendo el conjunto de alimentos
    Obteniendo el conjunto de gramos
    Obteniendo el porcentaje de proteínas
    Obteniendo el porcentaje de hidratos
    Obteniendo el porcentaje de lípidos
    Obteniendo valor calórico total del plato (FAILED - 1)

Failures:

  1) Plato Probando la clase Plato Obteniendo valor calórico total del plato
     Failure/Error: expect(@plato.valor_calorico).to eq(1003.6)

     NoMethodError:
       undefined method `valor_calorico' for #<Plato:0x000056071a291a90>
     # ./spec/alimentacion_spec.rb:316:in `block (3 levels) in <top (required)>'

Finished in 0.01616 seconds (files took 0.19317 seconds to load)
41 examples, 1 failure

Failed examples:

rspec ./spec/alimentacion_spec.rb:315 # Plato Probando la clase Plato Obteniendo valor calórico total del plato